//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project5.SuhasServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuhasServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findNearestStore", ReplyAction="http://tempuri.org/IService1/findNearestStoreResponse")]
        string findNearestStore(string zipcode, string storeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/findNearestStore", ReplyAction="http://tempuri.org/IService1/findNearestStoreResponse")]
        System.Threading.Tasks.Task<string> findNearestStoreAsync(string zipcode, string storeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/distanceCalulator", ReplyAction="http://tempuri.org/IService1/distanceCalulatorResponse")]
        string distanceCalulator(string zipcode1, string zipcode2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/distanceCalulator", ReplyAction="http://tempuri.org/IService1/distanceCalulatorResponse")]
        System.Threading.Tasks.Task<string> distanceCalulatorAsync(string zipcode1, string zipcode2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : project5.SuhasServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<project5.SuhasServiceRef.IService1>, project5.SuhasServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string findNearestStore(string zipcode, string storeName) {
            return base.Channel.findNearestStore(zipcode, storeName);
        }
        
        public System.Threading.Tasks.Task<string> findNearestStoreAsync(string zipcode, string storeName) {
            return base.Channel.findNearestStoreAsync(zipcode, storeName);
        }
        
        public string distanceCalulator(string zipcode1, string zipcode2) {
            return base.Channel.distanceCalulator(zipcode1, zipcode2);
        }
        
        public System.Threading.Tasks.Task<string> distanceCalulatorAsync(string zipcode1, string zipcode2) {
            return base.Channel.distanceCalulatorAsync(zipcode1, zipcode2);
        }
    }
}
